### ISSUE TITLE
With language-css, `#` shouldn't be treated as a comment

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#1484]
This might be obsolete, but in case it isn't... I've been experimenting with the angular_components docs, among other things specifying the language in code blocks, like this:

```
/// ```css
/// /* Make #myButton green with yellow text */
/// #myButton {
///   background: green;
///   color: yellow;
/// }
/// ```
```

GitHub styles that reasonably:

```css
/* Make #myButton green with yellow text */
#myButton {
  background: green;
  color: yellow;
}
```

Unfortunately, dartdoc treats the `#` as the start of a comment:
![image](https://user-images.githubusercontent.com/2164483/29691605-a33587d4-88e0-11e7-9e2e-2ed4b9f4f6b0.png)

I'm using 1.24.

```
$ dart --version
Dart VM version: 1.24.0 (Mon Jun 12 08:22:15 2017) on "macos_x64"
$ dartdoc --version
dartdoc version: 0.9.14-dev
```

Related to dart-lang/site-www#345.
