### ISSUE TITLE
Support custom categories for libraries within a package – and the SDK

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1610]
Allow organizing the libraries (on the left side of nav) into custom categories

Blocking https://github.com/dart-lang/sdk/issues/32297

**Comment by jcollins-g** [comment]
marking as P2 based on dartdoc triage priority (enhancements considered important but with no data indicating they are a big win)

**Comment by kevmoo** [comment]
I'd argue for P1 just because we are moving some `dart:` apis from `core` to `VM` – `mirrors` and `isolates` – and we want to help folks understand where they can be used!

**Comment by kevmoo** [comment]
Thank you!

**Comment by jcollins-g** [comment]
@kevmoo Just to let you know I haven't forgotten this.  With #1625 out of the way, now working on a steel thread through dartdoc to make dartdoc_options.yaml real.   But before I get much further, I'll outline the planned outcome:

dartdoc_options.yaml will understand (for now) exactly two fields, one for listing the subcategorization, and another for sorting the subcategories. 

Then we drop a dartdoc_options.yaml into the SDK like so:

```yaml
dartdoc:
  categoryOrder: ['VM', 'Web']
  categories:
    VM: ['dart:io', 'dart:cli']
    Web:
      - 'dart:html'
      - 'dart:indexed_db'
      - 'dart:js'
      - 'dart:js_util'
      - 'dart:svg'
      - 'dart:web_audio'
      - 'dart:web_gl'
      - 'dart:web_sql'
```

Dartdoc will show uncategorized items in the sidebar first, then will organize the others as listed under subheadings.
