### ISSUE TITLE
@tool snippet is not working

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [dart-lang/dartdoc#2161]
the `{@tool snippet} ` command is not working when generating an API document.
this is the code snippet : 
```
///{@tool snippet}
///discription
///```dart
/// code snippet
/// ``` 
/// {@end-tool}
```
can u please help me with this.

here is the error log : 
`error: unresolved export uri: "dart:html_common", from dart-html: (file:///C:/src/flutter/bin/cache/pkg/sky_engine/lib/html/html_dart2js.dart:17:9)`

![image](https://user-images.githubusercontent.com/61863686/76556832-4dccfe80-64c0-11ea-8549-c6048e4006f7.png)

**Comment by Yuvaraj-Gajaraj** [comment]
https://github.com/flutter/flutter/tree/master/dev/snippets#types-of-code-blocks This example is not working.

**Comment by jcollins-g** [comment]
Tool snippets have to be enabled and configured; they're not turned on by default because they can allow external programs to be executed.   `--allow-tools` must be passed in the dartdoc command line, and they have to be set up in `dartdoc_options.yaml`.  If you pass `--allow-tools`, the error messages may help you understand what needs to be done or help us help you.

**Comment by Yuvaraj-Gajaraj** [comment]
I have tried the `--allow-tools` in dartdoc command it says need to add a `dartdoc_optional.yaml` then I have added the dartdoc file with the following configuration 
```
dartdoc:
  tools:
    snippet:
      command: ["C:/src/flutter/dev/snippets/lib/main.dart", "--type=application"]
      description: "Creates application sample code documentation output from embedded documentation samples."
    sample:
      command: ["C:/src/flutter/dev/snippets/lib/main.dart", "--type=sample"]
      description: "Creates sample code documentation output from embedded documentation samples."
    dartpad:
      command: ["C:/src/flutter/dev/snippets/lib/main.dart", "--type=application", "--dartpad"]
      description: "Creates sample code documentation output from embedded documentation samples and displays it in an embedded DartPad."
```
after that I have run `dartdoc --allow-tools` it will encounter with the following error message
`Error: Error when reading '/C:/Users/YUVARA~1/AppData/Local/Temp/dartdoc_snapshot_cache_b29638ef-6a99-11ea-8411-0c96e683dec7/snapshot_0': The system cannot find the file specified.


, from dart-ui.FontFeature: (file:///C:/src/flutter/bin/cache/pkg/sky_engine/lib/ui/text.dart:177:7)
  error: tool execution failed: Tool "snippet" returned non-zero exit code (254) when run as "C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\Users\YUVARA~1\AppData\Local\Temp\dartdoc_snapshot_cache_b29638ef-6a99-11ea-8411-0c96e683dec7\snapshot_0 --type=application --template=stateless_widget_scaffold"`.

**Comment by jcollins-g** [comment]
@gspencergoog may have some insights here -- I've not attempted yet to use flutter doc tools to enhance other docs.

In any event, we should do better here in terms of explaining what's going on to the user.

**Comment by gspencergoog** [comment]
@Yuvaraj-Gajaraj The `snippet` tool is only designed to work with the Flutter source code, to generate our own API docs. If you're trying to use it for another project, you'll likely need to customize the code to work for your project. At the moment, we don't have plans to generalize it for other projects.

**Comment by JarrodCColburn** [comment]
I actually did get the snippets to work, but my solution was extremely hacky. 

I referenced the snippets package in my pubspec
```yaml
# file: pubspec.yaml
# add snippets package, using by local path, to dev_dependencies
dev_dependencies:
# ...
  snippets:
    path: $flutter/dev/snippets
```

I didn't know the best way to call `$snippets/lib/main.dart` as it isn't in executables (in snippet's package pubspec). So I wrote a script `call_snippets.dart` to call main, simply passing argument along. (Hacky I know)

```dart
// file: call_snippets.dart
// create this script
import 'dart:io';
import 'package:snippets/main.dart' as snipppets;

void main(List<String> argList) {
  // Change to flutter root
  Directory.current = Platform.environment['FLUTTER_ROOT'];
  return snipppets.main(argList);
}

```
I then reference that script in command in dartdoc_options
```yaml
# file: dartdoc_options.yaml
dartdoc:
    tools:
    # ...
      snippet:
        # call script
        command: ["call_snippets.dart", "--type=snippet"]
```


When executing `dartdoc` tool, to use Flutter's snippet styling, within  `$flutter/dev/docs` locate both `snipets.html` and `styles.html` and preface their paths each with `--header` flags.
In addition to this and `--allow-tools,` the need `--inject-html` flag must also be included.

Once docs are generated copy `$flutter/dev/docs/assets` directory into `$project_root/doc/api` to include Flutter's css and js files.

**Comment by JarrodCColburn** [comment]
Let me ask though  ...even if someone gets this working, would it affect their docs pushed to [pub.dev](pub.dev)? Is dartdoc run automatically without flags on push? Both [Dart](api.dart.dev/stable) and [Flutter](api.flutter.dev) host their own docs, so they can write custom scripts ( [dart](https://github.com/dart-lang/sdk/blob/master/tools/bots/dart_sdk.py) and [flutter](https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh) ) to push to their own servers. But how do the rest of us accomplish getting Flutter-like dartdocs on pub.dev without hosting a custom solution  ? 

I would think it might be in the `dartdoc_options.yaml`
```yaml
dartdoc:
    flags:
      - allow-tools
      - inject-html
    header:
      - snipets.html
      - styles.html
    assets:
      - assets
```
Would this open up security holes on dart.pub, allowing people to push custom html/js? 
Because of this, and since snippets are so useful, maybe the feature should be built into either dartdoc (or dart-services) where docs can be pushed to pub.dev.
