### ISSUE TITLE
memory usage going overboard

### ISSUE THREAD

**Issue by Freundschaft** [dart-lang/dartdoc#2237]
I have a relatively small application, but dartdoc consumes up to 2GB memory while running.
I understand that the reason for this is that dartdoc will initialize with all libraries before generating docs for my app.
Unfortunately right now this crashes my CI configuration, and I will make sure that memory will be increased on the runner, but is this going to be adressed in the future, or will I have to accept memory usage for doc generation?

Thanks & Best Regards
Qiong

**Comment by jcollins-g** [comment]
this is something of a known issue with dartdoc generally that we use too much memory.  If you can, please share any specifics to your application that you can (packages used, dartdoc version).

**Comment by Freundschaft** [comment]
dartdoc version: 0.31.0
I am using it with flutter, my packages include:

```
  cupertino_icons: ^0.1.3
  dots_indicator: ^1.0.0
  dio: ^3.0.9
  flutter_secure_storage: ^3.3.3
  provider: ^4.1.2
  get_it: ^4.0.2
  intl: ^0.16.1
  flutter_markdown: ^0.4.1
  sentry: ">=3.0.0 <4.0.0"
  flutter_dotenv: ^2.1.0
  url_launcher: ^5.4.10
  url_launcher_web: '>=0.1.1+6 <2.0.0'
  i18n_extension: ^1.3.9
  page_view_indicators: ^1.3.1
  gtag_analytics:
```
