### ISSUE TITLE
DartDoc fails on pub when adding a custom category and markdown file 

### ISSUE THREAD

**Issue by Equartey** [dart-lang/dartdoc#3575]
Hi yall, 

We're facing an issue where an error during the `dart doc` step prevents our API docs from generating on pub. 
Error can be seen in our [score log](https://pub.dev/packages/amplify_flutter/score/log.txt) and the relevant part being: 

```
Unhandled exception:
In categories definition for Auth, "markdown" resolves to the missing file /tmp/analyzerYYKSHG/pub-cache/hosted/20231102t094900-dot-dartlang-pub.appspot.com/amplify_core-1.6.1/doc/auth.md
#0      CategoryConfiguration.fromYamlMap (package:dartdoc/src/dartdoc_options.dart:102:13)
#1      _DartdocFileOption._valueAtFromFile (package:dartdoc/src/dartdoc_options.dart:951:28)
#2      _DartdocFileOption._valueAtFromFilesFirstFound (package:dartdoc/src/dartdoc_options.dart:889:15)
#3      _DartdocFileOption._valueAtFromFiles (package:dartdoc/src/dartdoc_options.dart:877:28)
#4      _DartdocFileOption.valueAt (package:dartdoc/src/dartdoc_options.dart:863:29)
#5      DartdocOptionContext.categories (package:dartdoc/src/dartdoc_options.dart:1253:31)
#6      new Category (package:dartdoc/src/model/category.dart:68:20)
#7      Package.initializeCategories (package:dartdoc/src/model/package.dart:292:23)
#8      PackageGraph.initializeCategories (package:dartdoc/src/model/package_graph.dart:165:15)
#9      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:93:14)
<asynchronous suspension>
#10     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:196:24)
<asynchronous suspension>
#11     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:244:24)
<asynchronous suspension>
#12     pubDartDoc (package:pub_dartdoc/pub_dartdoc.dart:32:19)
<asynchronous suspension>
#13     _dartdoc (package:pub_worker/src/bin/dartdoc_wrapper.dart:151:3)
<asynchronous suspension>
#14     main (package:pub_worker/src/bin/dartdoc_wrapper.dart:56:5)
<asynchronous suspension>
### Execution of dartdoc exited 255
STOPPED: 2023-11-07T05:09:15.336986Z
```

Our file structure can be seen [here](https://github.com/aws-amplify/amplify-flutter/tree/main/packages/amplify_core), and this is our `dartdoc_options.yaml`:

```yaml
dartdoc:
  categories:
    "Auth":
      markdown: doc/auth.md
  categoryOrder:
    - Auth
  favicon: doc/favicon.png
  nodoc:
    - lib/src/config/analytics/**
    - lib/src/config/api/**
    - lib/src/config/auth/**
    - lib/src/config/notifications/**
    - lib/src/config/storage/**
    - lib/src/config/amplify_plugin_config.dart
    - lib/src/config/amplify_plugin_registry.dart
    - lib/src/config/config_map.dart
    - lib/src/http/**
    - lib/src/platform/**
    - lib/src/plugin/**
    - lib/src/state_machine/**
    - lib/src/util/**
```

I could not reproduced locally as `dart doc .` succees and the custom category markdown file is working as intended. For some reason the file is being lost when the package is published. Any insight on the cause or resolution?
