### ISSUE TITLE
Infinite search bar loading issues

### ISSUE THREAD

**Issue by priyanuj-gogoi** [dart-lang/dartdoc#3614]
Happy New Year and here, comes the first issue of 2024!

When we try to define an undocumented category in `dartdoc_options.yaml` file, there is an issue where it's leading the docs to have an infinite search bar loading.

#### Steps to reproduce

*Using an official template for demo purpose.*

1. Create a new package
   ```sh
   dart create -t package test_pkg
   ```
2. Add a `@category` tag in the `Awesome` class located at `lib/src/test_pkg_base.dart`.
   ```dart
   /// Checks if you are awesome. Spoiler: you are.
   ///
   /// {@category Meow}
   class Awesome {
     bool get isAwesome => true;
   }
   ```
3. Create a `dartdoc_options.yaml` file in the package root and define the category in that file.
   ```yaml
   dartdoc:
     categories:
       Meow:
         # Using "CHANGELOG.md" as placeholder md file.
         markdown: CHANGELOG.md
   ```
4. Now, generate & view the docs.
   ```sh
   dart pub get
   dart doc
   ```

Here's the overall output of the docs: https://65957459aa11b00338461866--preeminent-axolotl-893ea2.netlify.app

Using Dart SDK: v3.2.4
