### ISSUE TITLE
add new items to categories

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#3617]
This is a feature request to be able to add new items to categories. Specifically, we'd like to add a non-library link in with other library items. So:

- Web
  - `package:web` (ext. link)
  - `dart:js_interop`
  - `dart:js_interop_unsafe`
- Web (Legacy)
  - `dart:html`
  - `dart:indexed_db`
  - `dart:js`

Above, most of the items are regular library doc links (like from https://api.dart.dev/stable/3.2.4/index.html), but the `package:web` is a name and an href to external docs (hosted at https://pub.dev/documentation/web/latest/).

**Comment by srawlins** [comment]
Yeah nice idea.

**Comment by srawlins** [comment]
Currently you can specify the categories in `dartdoc_options.yaml` like so:

```yaml
dartdoc:
  categories:
    One:
      markdown: one.md
    Two:
      markdown: two.md
  categoryOrder: ["One", "Two"]
```

We could add a field next to `markdown` called something like `external`? A list of mappings:

```yaml
dartdoc:
  categories:
    One:
      markdown: one.md
      external:
        - name: 'package:web'
          url: https://pub.dev/documentation/web/latest/
        - name: 'package:another'
        - url: ...
    Two:
      markdown: two.md
  categoryOrder: ["One", "Two"]
```
